import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "EasyConverter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="min-h-screen bg-[linear-gradient(90deg,rgba(2,0,36,1)_0%,rgba(10,49,122,1)_44%,rgba(17,70,150,1)_100%)]">
        {children}
      </body>
    </html>
  );
}
